#!/bin/sh
# Copyright (c) 2023 Aaron Ayub
# SPDX-License-Identifier: GPL-3.0-only

# Set up network namespace if not already done
ip netns add nsvpn
ip netns exec nsvpn ip link set lo up

# Setup namespaced nsswitch.conf
mkdir -p /etc/netns/nsvpn
if ! cp ./nsswitch.conf /etc/netns/nsvpn/nsswitch.conf; then
	echo "Could not write to nsswitch.conf file. Exiting early."
	exit 1
fi

# Set up firewall if the nsvpn table does not already exist
if ! ip netns exec nsvpn nft list table inet nsvpn >/dev/null && ! ip netns exec nsvpn nft -f ./nftables-commands.nft; then
	echo "Could not set up firewall. Exiting early."
	exit 1
fi

openvpn --route-noexec --ifconfig-noexec --script-security 2 --up-delay --up ./tunnelUp "$@"
