#!/bin/sh
# Copyright (c) 2023 Aaron Ayub
# SPDX-License_Identifier: GPL-3.0-only

# Set up network namespace if not already done
ip netns add nsvpn
ip netns exec nsvpn ip link set lo up

openvpn --route-noexec --ifconfig-noexec --script-security 2 --up-delay --up ./tunnelUp "$@"
