#!/bin/sh
# Copyright (c) 2023 Aaron Ayub
# SPDX-License-Identifier: GPL-3.0-only

# Move the tun0 device to the vpn namespace, configure it to use the endpoint and gateway provided by OpenVPN
/usr/sbin/ip link set tun0 netns nsvpn
/usr/sbin/ip netns exec nsvpn /usr/sbin/ip link set tun0 up
/usr/sbin/ip netns exec nsvpn /usr/sbin/ip addr add "$ifconfig_local" peer "$route_vpn_gateway" dev tun0
/usr/sbin/ip netns exec nsvpn /usr/sbin/ip route add default dev tun0
