#!/bin/bash
# Copyright (c) 2023-2024 Aaron Ayub
# SPDX-License-Identifier: GPL-3.0-only

# Move the tun0 device to the vpn namespace, configure it to use the endpoint and gateway
/usr/sbin/ip link set tun0 netns nsvpn
/usr/sbin/ip -n nsvpn link set tun0 up
# shellcheck disable=SC2154 # envvars below are provided by OpenVPN
/usr/sbin/ip -n nsvpn addr add "$ifconfig_local" peer "$route_vpn_gateway" dev tun0
/usr/sbin/ip -n nsvpn route add default dev tun0

# Update the resolv.conf file according to the OpenVPN config
mkdir -p /etc/netns/nsvpn
exec 3>/etc/netns/nsvpn/resolv.conf
search=""
i=0
while true; do
		i=$((i+1))
    optionNum="foreign_option_$i"
    opt="${!optionNum}"
    [ -z "$opt" ] && break
		# Gather the search directives
    if [ "$opt" != "${opt#dhcp-option DOMAIN}" ]; then
        search="${search} ${opt#dhcp-option DOMAIN}"
		# Write all nameserver directives
    elif [ "${opt}" != "${opt#dhcp-option DNS}" ]; then
        printf "nameserver %s\n" "${opt#dhcp-option DNS}" >&3
    fi
done

# Write search directive into resolv conf if available
[ -n "$search" ] && printf "search%s" "$search" >&3
exec 3>&-
chmod 644 /etc/netns/nsvpn/resolv.conf
